---
version: '3.8'

volumes:
  zookeeper:
  kafka:

services:
  zookeeper:
    image: bitnami/zookeeper:3.7.1-debian-11-r31  # Use Bitnami immutable tag
    restart: unless-stopped
    volumes:
      - zookeeper:/bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOO_PORT_NUMBER: 2181
      ZOO_SERVER_ID: 1
      ZOO_SERVERS: zoo1:2888:3888::1
      ZOO_LOG_LEVEL: INFO

  kafka:
    image: bitnami/kafka:3.2.1-debian-11-r5  # Use Bitnami immutable tag
    restart: unless-stopped
    depends_on:
      - zookeeper
    volumes:
      - kafka:/bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
